import fs from 'node:fs';
import path from 'node:path';
import { build } from 'esbuild';

const outFile = path.resolve('dist/architecture-agent.mjs');
const generatedAssetsFile = path.resolve('lib/assets.generated.mjs');
const assetDirs = ['prompts', 'workflows', 'templates'];

const assets = {};
for (const dir of assetDirs) {
  const absDir = path.resolve(dir);
  const entries = fs.readdirSync(absDir, { withFileTypes: true });
  const bucket = {};

  for (const entry of entries) {
    if (!entry.isFile()) {
      continue;
    }

    const filePath = path.join(absDir, entry.name);
    bucket[entry.name] = fs.readFileSync(filePath, 'utf8');
  }

  assets[dir] = bucket;
}

const generatedContent = [
  '// Auto-generated by scripts/build.mjs. Do not edit manually.',
  `export const ASSETS = ${JSON.stringify(assets)};`,
  ''
].join('\n');

fs.writeFileSync(generatedAssetsFile, generatedContent, 'utf8');

await build({
  entryPoints: ['bin/architecture-agent.mjs'],
  outfile: outFile,
  bundle: true,
  minify: true,
  sourcemap: false,
  platform: 'node',
  target: 'node18',
  format: 'esm',
  legalComments: 'none',
  banner: {
    js: '#!/usr/bin/env node'
  }
});

fs.chmodSync(outFile, 0o755);
console.log(`Built ${outFile}`);
